name: Daily Commit

on:
  schedule:
    # Runs at 07:30 UTC every day (you can adjust the time)
    - cron: "30 7 * * *"
  workflow_dispatch:  # allow manual trigger

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit with email 24f2006676@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit [skip ci]" || echo "No changes to commit"

      - name: Push changes to main branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git main
